package com.onroad.custom;

public enum KinshipLevel {
    FATHER, MOTHER, BROTHER, UNCLE, COUSIN, FRIEND, NEPHEW, STEPSON, STEPMOTHER, SON, DAUGHTERINLAW, FATHERINLAW, OTHER, BOSS, EMPLOYEE, NEIGHBOR
}
